[env:esp32dev]
platform = espressif32 @ ~6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM3
monitor_port = COM3
monitor_filters = default, esp32_exception_decoder
lib_deps = 
	ottowinter/ESPAsyncWebServer-esphome @ ^3.0.0
	esphome/AsyncTCP-esphome @ ^2.0.0
	TaskScheduler
	ArduinoJson
	alanswx/ESPAsyncWiFiManager @ ^0.31
	NTPClient
	TFT_eSPI

	